var codes = {
    "abw": "aruba",
    "afg": "afghanistan",
    "ago": "angola",
    "aia": "anguilla",
    "ala": "åland islands",
    "alb": "albania",
    "and": "andorra",
    "ant": "netherlands antilles",
    "are": "united arab emirates",
    "arg": "argentina",
    "arm": "armenia",
    "asm": "american samoa",
    "ata": "antarctica",
    "atf": "french southern territories",
    "atg": "antigua and barbuda",
    "aus": "australia",
    "aut": "austria",
    "aze": "azerbaijan",
    "bdi": "burundi",
    "bel": "belgium",
    "ben": "benin",
    "bfa": "burkina faso",
    "bgd": "bangladesh",
    "bgr": "bulgaria",
    "bhr": "bahrain",
    "bhs": "bahamas",
    "bih": "bosnia and herzegovina",
    "blm": "saint barthélemy",
    "blr": "belarus",
    "blz": "belize",
    "bmu": "bermuda",
    "bol": "bolivia, plurinational state of",
    "bra": "brazil",
    "brb": "barbados",
    "brn": "brunei darussalam",
    "btn": "bhutan",
    "bvt": "bouvet island",
    "bwa": "botswana",
    "caf": "central african republic",
    "can": "canada",
    "cck": "cocos (keeling) islands",
    "che": "switzerland",
    "chl": "chile",
    "chn": "china",
    "civ": "côte d'ivoire",
    "cmr": "cameroon",
    "cod": "congo, the democratic republic of the",
    "cog": "congo",
    "cok": "cook islands",
    "col": "colombia",
    "com": "comoros",
    "cpv": "cape verde",
    "cri": "costa rica",
    "cub": "cuba",
    "cxr": "christmas island",
    "cym": "cayman islands",
    "cyp": "cyprus",
    "cze": "czech republic",
    "deu": "germany",
    "dji": "djibouti",
    "dma": "dominica",
    "dnk": "denmark",
    "dom": "dominican republic",
    "dza": "algeria",
    "ecu": "ecuador",
    "egy": "egypt",
    "eri": "eritrea",
    "esh": "western sahara",
    "esp": "spain",
    "est": "estonia",
    "eth": "ethiopia",
    "fin": "finland",
    "fji": "fiji",
    "flk": "falkland islands (malvinas)",
    "fra": "france",
    "fro": "faroe islands",
    "fsm": "micronesia, federated states of",
    "gab": "gabon",
    "gbr": "united kingdom",
    "geo": "georgia",
    "ggy": "guernsey",
    "gha": "ghana",
    "gib": "gibraltar",
    "gin": "guinea",
    "glp": "guadeloupe",
    "gmb": "gambia",
    "gnb": "guinea-bissau",
    "gnq": "equatorial guinea",
    "grc": "greece",
    "grd": "grenada",
    "grl": "greenland",
    "gtm": "guatemala",
    "guf": "french guiana",
    "gum": "guam",
    "guy": "guyana",
    "hkg": "hong kong",
    "hmd": "heard island and mcdonald islands",
    "hnd": "honduras",
    "hrv": "croatia",
    "hti": "haiti",
    "hun": "hungary",
    "idn": "indonesia",
    "imn": "isle of man",
    "ind": "india",
    "iot": "british indian ocean territory",
    "irl": "ireland",
    "irn": "iran, islamic republic of",
    "irq": "iraq",
    "isl": "iceland",
    "isr": "israel",
    "ita": "italy",
    "jam": "jamaica",
    "jey": "jersey",
    "jor": "jordan",
    "jpn": "japan",
    "kaz": "kazakhstan",
    "ken": "kenya",
    "kgz": "kyrgyzstan",
    "khm": "cambodia",
    "kir": "kiribati",
    "kna": "saint kitts and nevis",
    "kor": "korea, republic of",
    "kwt": "kuwait",
    "lao": "lao people's democratic republic",
    "lbn": "lebanon",
    "lbr": "liberia",
    "lby": "libyan arab jamahiriya",
    "lca": "saint lucia",
    "lie": "liechtenstein",
    "lka": "sri lanka",
    "lso": "lesotho",
    "ltu": "lithuania",
    "lux": "luxembourg",
    "lva": "latvia",
    "mac": "macao",
    "maf": "saint martin (french part)",
    "mar": "morocco",
    "mco": "monaco",
    "mda": "moldova",
    "mdg": "madagascar",
    "mdv": "maldives",
    "mex": "mexico",
    "mhl": "marshall islands",
    "mkd": "macedonia, the former yugoslav republic of",
    "mli": "mali",
    "mlt": "malta",
    "mmr": "myanmar",
    "mne": "montenegro",
    "mng": "mongolia",
    "mnp": "northern mariana islands",
    "moz": "mozambique",
    "mrt": "mauritania",
    "msr": "montserrat",
    "mtq": "martinique",
    "mus": "mauritius",
    "mwi": "malawi",
    "mys": "malaysia",
    "myt": "mayotte",
    "nam": "namibia",
    "ncl": "new caledonia",
    "ner": "niger",
    "nfk": "norfolk island",
    "nga": "nigeria",
    "nic": "nicaragua",
    "niu": "niue",
    "nld": "netherlands",
    "nor": "norway",
    "npl": "nepal",
    "nru": "nauru",
    "nzl": "new zealand",
    "omn": "oman",
    "pak": "pakistan",
    "pan": "panama",
    "pcn": "pitcairn",
    "per": "peru",
    "phl": "philippines",
    "plw": "palau",
    "png": "papua new guinea",
    "pol": "poland",
    "pri": "puerto rico",
    "prk": "korea, democratic people's republic of",
    "prt": "portugal",
    "pry": "paraguay",
    "pse": "palestinian territory, occupied",
    "pyf": "french polynesia",
    "qat": "qatar",
    "reu": "réunion",
    "rou": "romania",
    "rus": "russian federation",
    "rwa": "rwanda",
    "sau": "saudi arabia",
    "sdn": "sudan",
    "sen": "senegal",
    "sgp": "singapore",
    "sgs": "south georgia and the south sandwich islands",
    "shn": "saint helena, ascension and tristan da cunha",
    "sjm": "svalbard and jan mayen",
    "slb": "solomon islands",
    "sle": "sierra leone",
    "slv": "el salvador",
    "smr": "san marino",
    "som": "somalia",
    "spm": "saint pierre and miquelon",
    "srb": "serbia",
    "stp": "sao tome and principe",
    "sur": "suriname",
    "svk": "slovakia",
    "svn": "slovenia",
    "swe": "sweden",
    "swz": "swaziland",
    "syc": "seychelles",
    "syr": "syrian arab republic",
    "tca": "turks and caicos islands",
    "tcd": "chad",
    "tgo": "togo",
    "tha": "thailand",
    "tjk": "tajikistan",
    "tkl": "tokelau",
    "tkm": "turkmenistan",
    "tls": "timor-leste",
    "ton": "tonga",
    "tto": "trinidad and tobago",
    "tun": "tunisia",
    "tur": "turkey",
    "tuv": "tuvalu",
    "twn": "taiwan, province of china",
    "tza": "tanzania, united republic of",
    "uga": "uganda",
    "ukr": "ukraine",
    "umi": "united states minor outlying islands",
    "ury": "uruguay",
    "usa": "united states",
    "uzb": "uzbekistan",
    "vat": "holy see (vatican city state)",
    "vct": "saint vincent and the grenadines",
    "ven": "venezuela, bolivarian republic of",
    "vgb": "virgin islands, british",
    "vir": "virgin islands, u.s.",
    "vnm": "viet nam",
    "vut": "vanuatu",
    "wlf": "wallis and futuna",
    "wsm": "samoa",
    "yem": "yemen",
    "zaf": "south africa",
    "zmb": "zambia",
    "zwe": "zimbabwe",
}