var countries =  [
  { value: "abw", text: "Aruba" },
  { value: "afg", text: "Afghanistan" },
  { value: "ago", text: "Angola" },
  { value: "aia", text: "Anguilla" },
  { value: "ala", text: "Åland Islands" },
  { value: "alb", text: "Albania" },
  { value: "and", text: "Andorra" },
  { value: "ant", text: "Netherlands Antilles" },
  { value: "are", text: "United Arab Emirates" },
  { value: "arg", text: "Argentina" },
  { value: "arm", text: "Armenia" },
  { value: "asm", text: "American Samoa" },
  { value: "ata", text: "Antarctica" },
  { value: "atf", text: "French Southern Territories" },
  { value: "atg", text: "Antigua and Barbuda" },
  { value: "aus", text: "Australia" },
  { value: "aut", text: "Austria" },
  { value: "aze", text: "Azerbaijan" },
  { value: "bdi", text: "Burundi" },
  { value: "bel", text: "Belgium" },
  { value: "ben", text: "Benin" },
  { value: "bfa", text: "Burkina Faso" },
  { value: "bgd", text: "Bangladesh" },
  { value: "bgr", text: "Bulgaria" },
  { value: "bhr", text: "Bahrain" },
  { value: "bhs", text: "Bahamas" },
  { value: "bih", text: "Bosnia and Herzegovina" },
  { value: "blm", text: "Saint Barthélemy" },
  { value: "blr", text: "Belarus" },
  { value: "blz", text: "Belize" },
  { value: "bmu", text: "Bermuda" },
  { value: "bol", text: "Bolivia, Plurinational State of" },
  { value: "bra", text: "Brazil" },
  { value: "brb", text: "Barbados" },
  { value: "brn", text: "Brunei Darussalam" },
  { value: "btn", text: "Bhutan" },
  { value: "bvt", text: "Bouvet Island" },
  { value: "bwa", text: "Botswana" },
  { value: "caf", text: "Central African Republic" },
  { value: "can", text: "Canada" },
  { value: "cck", text: "Cocos (Keeling) Islands" },
  { value: "che", text: "Switzerland" },
  { value: "chl", text: "Chile" },
  { value: "chn", text: "China" },
  { value: "civ", text: "Côte d'Ivoire" },
  { value: "cmr", text: "Cameroon" },
  { value: "cod", text: "Congo, the Democratic Republic of the" },
  { value: "cog", text: "Congo" },
  { value: "cok", text: "Cook Islands" },
  { value: "col", text: "Colombia" },
  { value: "com", text: "Comoros" },
  { value: "cpv", text: "Cape Verde" },
  { value: "cri", text: "Costa Rica" },
  { value: "cub", text: "Cuba" },
  { value: "cxr", text: "Christmas Island" },
  { value: "cym", text: "Cayman Islands" },
  { value: "cyp", text: "Cyprus" },
  { value: "cze", text: "Czech Republic" },
  { value: "deu", text: "Germany" },
  { value: "dji", text: "Djibouti" },
  { value: "dma", text: "Dominica" },
  { value: "dnk", text: "Denmark" },
  { value: "dom", text: "Dominican Republic" },
  { value: "dza", text: "Algeria" },
  { value: "ecu", text: "Ecuador" },
  { value: "egy", text: "Egypt" },
  { value: "eri", text: "Eritrea" },
  { value: "esh", text: "Western Sahara" },
  { value: "esp", text: "Spain" },
  { value: "est", text: "Estonia" },
  { value: "eth", text: "Ethiopia" },
  { value: "fin", text: "Finland" },
  { value: "fji", text: "Fiji" },
  { value: "flk", text: "Falkland Islands (Malvinas)" },
  { value: "fra", text: "France" },
  { value: "fro", text: "Faroe Islands" },
  { value: "fsm", text: "Micronesia, Federated States of" },
  { value: "gab", text: "Gabon" },
  { value: "gbr", text: "United Kingdom" },
  { value: "geo", text: "Georgia" },
  { value: "ggy", text: "Guernsey" },
  { value: "gha", text: "Ghana" },
  { value: "gib", text: "Gibraltar" },
  { value: "gin", text: "Guinea" },
  { value: "glp", text: "Guadeloupe" },
  { value: "gmb", text: "Gambia" },
  { value: "gnb", text: "Guinea-Bissau" },
  { value: "gnq", text: "Equatorial Guinea" },
  { value: "grc", text: "Greece" },
  { value: "grd", text: "Grenada" },
  { value: "grl", text: "Greenland" },
  { value: "gtm", text: "Guatemala" },
  { value: "guf", text: "French Guiana" },
  { value: "gum", text: "Guam" },
  { value: "guy", text: "Guyana" },
  { value: "hkg", text: "Hong Kong" },
  { value: "hmd", text: "Heard Island and Mcdonald Islands" },
  { value: "hnd", text: "Honduras" },
  { value: "hrv", text: "Croatia" },
  { value: "hti", text: "Haiti" },
  { value: "hun", text: "Hungary" },
  { value: "idn", text: "Indonesia" },
  { value: "imn", text: "Isle of Man" },
  { value: "ind", text: "India" },
  { value: "iot", text: "British Indian Ocean Territory" },
  { value: "irl", text: "Ireland" },
  { value: "irn", text: "Iran, Islamic Republic of" },
  { value: "irq", text: "Iraq" },
  { value: "isl", text: "Iceland" },
  { value: "isr", text: "Israel" },
  { value: "ita", text: "Italy" },
  { value: "jam", text: "Jamaica" },
  { value: "jey", text: "Jersey" },
  { value: "jor", text: "Jordan" },
  { value: "jpn", text: "Japan" },
  { value: "kaz", text: "Kazakhstan" },
  { value: "ken", text: "Kenya" },
  { value: "kgz", text: "Kyrgyzstan" },
  { value: "khm", text: "Cambodia" },
  { value: "kir", text: "Kiribati" },
  { value: "kna", text: "Saint Kitts and Nevis" },
  { value: "kor", text: "Korea, Republic of" },
  { value: "kwt", text: "Kuwait" },
  { value: "lao", text: "Lao People's Democratic Republic" },
  { value: "lbn", text: "Lebanon" },
  { value: "lbr", text: "Liberia" },
  { value: "lby", text: "Libyan Arab Jamahiriya" },
  { value: "lca", text: "Saint Lucia" },
  { value: "lie", text: "Liechtenstein" },
  { value: "lka", text: "Sri Lanka" },
  { value: "lso", text: "Lesotho" },
  { value: "ltu", text: "Lithuania" },
  { value: "lux", text: "Luxembourg" },
  { value: "lva", text: "Latvia" },
  { value: "mac", text: "Macao" },
  { value: "maf", text: "Saint Martin (French Part)" },
  { value: "mar", text: "Morocco" },
  { value: "mco", text: "Monaco" },
  { value: "mda", text: "Moldova" },
  { value: "mdg", text: "Madagascar" },
  { value: "mdv", text: "Maldives" },
  { value: "mex", text: "Mexico" },
  { value: "mhl", text: "Marshall Islands" },
  { value: "mkd", text: "Macedonia, the Former Yugoslav Republic of" },
  { value: "mli", text: "Mali" },
  { value: "mlt", text: "Malta" },
  { value: "mmr", text: "Myanmar" },
  { value: "mne", text: "Montenegro" },
  { value: "mng", text: "Mongolia" },
  { value: "mnp", text: "Northern Mariana Islands" },
  { value: "moz", text: "Mozambique" },
  { value: "mrt", text: "Mauritania" },
  { value: "msr", text: "Montserrat" },
  { value: "mtq", text: "Martinique" },
  { value: "mus", text: "Mauritius" },
  { value: "mwi", text: "Malawi" },
  { value: "mys", text: "Malaysia" },
  { value: "myt", text: "Mayotte" },
  { value: "nam", text: "Namibia" },
  { value: "ncl", text: "New Caledonia" },
  { value: "ner", text: "Niger" },
  { value: "nfk", text: "Norfolk Island" },
  { value: "nga", text: "Nigeria" },
  { value: "nic", text: "Nicaragua" },
  { value: "niu", text: "Niue" },
  { value: "nld", text: "Netherlands" },
  { value: "nor", text: "Norway" },
  { value: "npl", text: "Nepal" },
  { value: "nru", text: "Nauru" },
  { value: "nzl", text: "New Zealand" },
  { value: "omn", text: "Oman" },
  { value: "pak", text: "Pakistan" },
  { value: "pan", text: "Panama" },
  { value: "pcn", text: "Pitcairn" },
  { value: "per", text: "Peru" },
  { value: "phl", text: "Philippines" },
  { value: "plw", text: "Palau" },
  { value: "png", text: "Papua New Guinea" },
  { value: "pol", text: "Poland" },
  { value: "pri", text: "Puerto Rico" },
  { value: "prk", text: "Korea, Democratic People's Republic of" },
  { value: "prt", text: "Portugal" },
  { value: "pry", text: "Paraguay" },
  { value: "pse", text: "Palestinian Territory, Occupied" },
  { value: "pyf", text: "French Polynesia" },
  { value: "qat", text: "Qatar" },
  { value: "reu", text: "Réunion" },
  { value: "rou", text: "Romania" },
  { value: "rus", text: "Russian Federation" },
  { value: "rwa", text: "Rwanda" },
  { value: "sau", text: "Saudi Arabia" },
  { value: "sdn", text: "Sudan" },
  { value: "sen", text: "Senegal" },
  { value: "sgp", text: "Singapore" },
  { value: "sgs", text: "South Georgia and the South Sandwich Islands" },
  { value: "shn", text: "Saint Helena, Ascension and Tristan Da Cunha" },
  { value: "sjm", text: "Svalbard and Jan Mayen" },
  { value: "slb", text: "Solomon Islands" },
  { value: "sle", text: "Sierra Leone" },
  { value: "slv", text: "El Salvador" },
  { value: "smr", text: "San Marino" },
  { value: "som", text: "Somalia" },
  { value: "spm", text: "Saint Pierre and Miquelon" },
  { value: "srb", text: "Serbia" },
  { value: "stp", text: "Sao Tome and Principe" },
  { value: "sur", text: "Suriname" },
  { value: "svk", text: "Slovakia" },
  { value: "svn", text: "Slovenia" },
  { value: "swe", text: "Sweden" },
  { value: "swz", text: "Swaziland" },
  { value: "syc", text: "Seychelles" },
  { value: "syr", text: "Syrian Arab Republic" },
  { value: "tca", text: "Turks and Caicos Islands" },
  { value: "tcd", text: "Chad" },
  { value: "tgo", text: "Togo" },
  { value: "tha", text: "Thailand" },
  { value: "tjk", text: "Tajikistan" },
  { value: "tkl", text: "Tokelau" },
  { value: "tkm", text: "Turkmenistan" },
  { value: "tls", text: "Timor-Leste" },
  { value: "ton", text: "Tonga" },
  { value: "tto", text: "Trinidad and Tobago" },
  { value: "tun", text: "Tunisia" },
  { value: "tur", text: "Turkey" },
  { value: "tuv", text: "Tuvalu" },
  { value: "twn", text: "Taiwan, Province of China" },
  { value: "tza", text: "Tanzania, United Republic of" },
  { value: "uga", text: "Uganda" },
  { value: "ukr", text: "Ukraine" },
  { value: "umi", text: "United States Minor Outlying Islands" },
  { value: "ury", text: "Uruguay" },
  { value: "usa", text: "United States" },
  { value: "uzb", text: "Uzbekistan" },
  { value: "vat", text: "Holy See (Vatican City State)" },
  { value: "vct", text: "Saint Vincent and the Grenadines" },
  { value: "ven", text: "Venezuela, Bolivarian Republic of" },
  { value: "vgb", text: "Virgin Islands, British" },
  { value: "vir", text: "Virgin Islands, U.S." },
  { value: "vnm", text: "Viet Nam" },
  { value: "vut", text: "Vanuatu" },
  { value: "wlf", text: "Wallis and Futuna" },
  { value: "wsm", text: "Samoa" },
  { value: "yem", text: "Yemen" },
  { value: "zaf", text: "South Africa" },
  { value: "zmb", text: "Zambia" },
  { value: "zwe", text: "Zimbabwe" }, 
]