 var countries = [
  { name: "Afghanistan", iso3: "afg" },
  { name: "Albania", iso3: "alb" },
  { name: "Algeria", iso3: "dza" },
  { name: "Andorra", iso3: "and" },
  { name: "Angola", iso3: "ago" },
  { name: "Antigua and Barbuda", iso3: "atg" },
  { name: "Argentina", iso3: "arg" },
  { name: "Armenia", iso3: "arm" },
  { name: "Australia", iso3: "aus" },
  { name: "Austria", iso3: "aut" },
  { name: "Azerbaijan", iso3: "aze" },
  { name: "Bahamas", iso3: "bhs" },
  { name: "Bahrain", iso3: "bhr" },
  { name: "Bangladesh", iso3: "bgd" },
  { name: "Barbados", iso3: "brb" },
  { name: "Belarus", iso3: "blr" },
  { name: "Belgium", iso3: "bel" },
  { name: "Belize", iso3: "blz" },
  { name: "Benin", iso3: "ben" },
  { name: "Bhutan", iso3: "btn" },
  { name: "Bolivia", iso3: "bol" },
  { name: "Bosnia and Herzegovina", iso3: "bih" },
  { name: "Botswana", iso3: "bwa" },
  { name: "Brazil", iso3: "bra" },
  { name: "Brunei", iso3: "brn" },
  { name: "Bulgaria", iso3: "bgr" },
  { name: "Burkina Faso", iso3: "bfa" },
  { name: "Burma", iso3: "mmr" },
  { name: "Burundi", iso3: "bdi" },
  { name: "Cabo Verde", iso3: "cpv" },
  { name: "Cambodia", iso3: "khm" },
  { name: "Cameroon", iso3: "cmr" },
  { name: "Canada", iso3: "can" },
  { name: "Central African Republic", iso3: "caf" },
  { name: "Chad", iso3: "tcd" },
  { name: "Chile", iso3: "chl" },
  { name: "China", iso3: "chn" },
  { name: "Colombia", iso3: "col" },
  { name: "Congo (Brazzaville)", iso3: "cog" },
  { name: "Congo (Kinshasa)", iso3: "cod" },
  { name: "Costa Rica", iso3: "cri" },
  { name: "Cote d'Ivoire", iso3: "civ" },
  { name: "Croatia", iso3: "hrv" },
  { name: "Cuba", iso3: "cub" },
  { name: "Cyprus", iso3: "cyp" },
  { name: "Czechia", iso3: "cze" },
  { name: "Denmark", iso3: "dnk" },
  { name: "Djibouti", iso3: "dji" },
  { name: "Dominica", iso3: "dma" },
  { name: "Dominican Republic", iso3: "dom" },
  { name: "Ecuador", iso3: "ecu" },
  { name: "Egypt", iso3: "egy" },
  { name: "El Salvador", iso3: "slv" },
  { name: "Equatorial Guinea", iso3: "gnq" },
  { name: "Eritrea", iso3: "eri" },
  { name: "Estonia", iso3: "est" },
  { name: "Eswatini", iso3: "swz" },
  { name: "Ethiopia", iso3: "eth" },
  { name: "Fiji", iso3: "fji" },
  { name: "Finland", iso3: "fin" },
  { name: "France", iso3: "fra" },
  { name: "Gabon", iso3: "gab" },
  { name: "Gambia", iso3: "gmb" },
  { name: "Georgia", iso3: "geo" },
  { name: "Germany", iso3: "deu" },
  { name: "Ghana", iso3: "gha" },
  { name: "Greece", iso3: "grc" },
  { name: "Grenada", iso3: "grd" },
  { name: "Guatemala", iso3: "gtm" },
  { name: "Guinea-Bissau", iso3: "gnb" },
  { name: "Guinea", iso3: "gin" },
  { name: "Guyana", iso3: "guy" },
  { name: "Haiti", iso3: "hti" },
  { name: "Holy See", iso3: "vat" },
  { name: "Honduras", iso3: "hnd" },
  { name: "Hungary", iso3: "hun" },
  { name: "Iceland", iso3: "isl" },
  { name: "India", iso3: "ind" },
  { name: "Indonesia", iso3: "idn" },
  { name: "Iran", iso3: "irn" },
  { name: "Iraq", iso3: "irq" },
  { name: "Ireland", iso3: "irl" },
  { name: "Israel", iso3: "isr" },
  { name: "Italy", iso3: "ita" },
  { name: "Jamaica", iso3: "jam" },
  { name: "Japan", iso3: "jpn" },
  { name: "Jordan", iso3: "jor" },
  { name: "Kazakhstan", iso3: "kaz" },
  { name: "Kenya", iso3: "ken" },
  { name: "Korea, South", iso3: "kor" },
  { name: "Kosovo", iso3: "rks" },
  { name: "Kuwait", iso3: "kwt" },
  { name: "Kyrgyzstan", iso3: "kgz" },
  { name: "Laos", iso3: "lao" },
  { name: "Latvia", iso3: "lva" },
  { name: "Lebanon", iso3: "lbn" },
  { name: "Liberia", iso3: "lbr" },
  { name: "Libya", iso3: "lby" },
  { name: "Liechtenstein", iso3: "lie" },
  { name: "Lithuania", iso3: "ltu" },
  { name: "Luxembourg", iso3: "lux" },
  { name: "Madagascar", iso3: "mdg" },
  { name: "Malaysia", iso3: "mys" },
  { name: "Maldives", iso3: "mdv" },
  { name: "Mali", iso3: "mli" },
  { name: "Malta", iso3: "mlt" },
  { name: "Mauritania", iso3: "mrt" },
  { name: "Mauritius", iso3: "mus" },
  { name: "Mexico", iso3: "mex" },
  { name: "Moldova", iso3: "mda" },
  { name: "Monaco", iso3: "mco" },
  { name: "Mongolia", iso3: "mng" },
  { name: "Montenegro", iso3: "mne" },
  { name: "Morocco", iso3: "mar" },
  { name: "Mozambique", iso3: "moz" },
  { name: "Namibia", iso3: "nam" },
  { name: "Nepal", iso3: "npl" },
  { name: "Netherlands", iso3: "nld" },
  { name: "New Zealand", iso3: "nzl" },
  { name: "Nicaragua", iso3: "nic" },
  { name: "Niger", iso3: "ner" },
  { name: "Nigeria", iso3: "nga" },
  { name: "North Macedonia", iso3: "mkd" },
  { name: "Norway", iso3: "nor" },
  { name: "Oman", iso3: "omn" },
  { name: "Pakistan", iso3: "pak" },
  { name: "Panama", iso3: "pan" },
  { name: "Papua New Guinea", iso3: "png" },
  { name: "Paraguay", iso3: "pry" },
  { name: "Peru", iso3: "per" },
  { name: "Philippines", iso3: "phl" },
  { name: "Poland", iso3: "pol" },
  { name: "Portugal", iso3: "prt" },
  { name: "Qatar", iso3: "qat" },
  { name: "Romania", iso3: "rou" },
  { name: "Russia", iso3: "rus" },
  { name: "Rwanda", iso3: "rwa" },
  { name: "Saint Kitts and Nevis", iso3: "kna" },
  { name: "Saint Lucia", iso3: "lca" },
  { name: "Saint Vincent and the Grenadines", iso3: "vct" },
  { name: "San Marino", iso3: "smr" },
  { name: "Saudi Arabia", iso3: "sau" },
  { name: "Senegal", iso3: "sen" },
  { name: "Serbia", iso3: "srb" },
  { name: "Seychelles", iso3: "syc" },
  { name: "Sierra Leone", iso3: "sle" },
  { name: "Singapore", iso3: "sgp" },
  { name: "Slovakia", iso3: "svk" },
  { name: "Slovenia", iso3: "svn" },
  { name: "Somalia", iso3: "som" },
  { name: "South Africa", iso3: "zaf" },
  { name: "Spain", iso3: "esp" },
  { name: "Sri Lanka", iso3: "lka" },
  { name: "Sudan", iso3: "sdn" },
  { name: "Suriname", iso3: "sur" },
  { name: "Sweden", iso3: "swe" },
  { name: "Switzerland", iso3: "che" },
  { name: "Syria", iso3: "syr" },
  { name: "Taiwan*", iso3: "twn" },
  { name: "Tanzania", iso3: "tza" },
  { name: "Thailand", iso3: "tha" },
  { name: "Timor-Leste", iso3: "tls" },
  { name: "Togo", iso3: "tgo" },
  { name: "Trinidad and Tobago", iso3: "tto" },
  { name: "Tunisia", iso3: "tun" },
  { name: "Turkey", iso3: "tur" },
  { name: "Uganda", iso3: "uga" },
  { name: "Ukraine", iso3: "ukr" },
  { name: "United Arab Emirates", iso3: "are" },
  { name: "United Kingdom", iso3: "gbr" },
  { name: "Uruguay", iso3: "ury" },
  { name: "US", iso3: "usa" },
  { name: "Uzbekistan", iso3: "uzb" },
  { name: "Venezuela", iso3: "ven" },
  { name: "Viet Nam", iso3: "vnm" },
  { name: "West Bank and Gaza", iso3: "pse" },
  { name: "Zambia", iso3: "zmb" },
  { name: "Zimbabwe", iso3: "zwe" }
 ]
